/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package minorpack;

/**
 *
 * @author Manager
 */
public class BiggiesBurger extends javax.swing.JFrame {
    public int SubTotal = 0;
     public int SubTotal1 = 0;
     public int SubTotal2 = 0; 

    /**
     * Creates new form BiggiesBurger
     */
    public BiggiesBurger() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbPaneer = new javax.swing.JCheckBox();
        cbChicken = new javax.swing.JCheckBox();
        cbOnion = new javax.swing.JCheckBox();
        sQuantity = new javax.swing.JSpinner();
        sQuantity2 = new javax.swing.JSpinner();
        sQuantity1 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfTotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        bADD = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tfItem = new javax.swing.JTextField();
        bREMOVE = new javax.swing.JButton();
        bADD1 = new javax.swing.JButton();
        bADD2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,70));

        jLabel3.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Total");

        jLabel9.setFont(new java.awt.Font("Perpetua", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Price");

        jLabel4.setFont(new java.awt.Font("Perpetua", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quantity");

        cbPaneer.setFont(new java.awt.Font("Script MT Bold", 0, 20)); // NOI18N
        cbPaneer.setForeground(new java.awt.Color(255, 255, 255));
        cbPaneer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPaneerActionPerformed(evt);
            }
        });

        cbChicken.setBackground(new java.awt.Color(255, 255, 255));
        cbChicken.setFont(new java.awt.Font("Script MT Bold", 0, 20)); // NOI18N
        cbChicken.setForeground(new java.awt.Color(255, 255, 255));
        cbChicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbChickenActionPerformed(evt);
            }
        });

        cbOnion.setFont(new java.awt.Font("Script MT Bold", 0, 20)); // NOI18N
        cbOnion.setForeground(new java.awt.Color(255, 255, 255));
        cbOnion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOnionActionPerformed(evt);
            }
        });

        sQuantity.setValue(0);
        sQuantity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sQuantityStateChanged(evt);
            }
        });

        sQuantity2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sQuantity2StateChanged(evt);
            }
        });

        sQuantity1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sQuantity1StateChanged(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Script MT Bold", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("180");

        jLabel8.setFont(new java.awt.Font("Script MT Bold", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("145");

        jLabel7.setFont(new java.awt.Font("Script MT Bold", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("119");

        tfTotal.setEditable(false);
        tfTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTotalActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Perpetua", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Menu");

        bADD.setBackground(new java.awt.Color(255, 102, 51));
        bADD.setFont(new java.awt.Font("Lucida Bright", 0, 15)); // NOI18N
        bADD.setForeground(new java.awt.Color(255, 255, 255));
        bADD.setText("Add to Cart");
        bADD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bADDActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Script MT Bold", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cheese Chicken Burger");

        jLabel5.setFont(new java.awt.Font("Script MT Bold", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Club Veg Burger");

        jLabel11.setFont(new java.awt.Font("Script MT Bold", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Aloo Tikki Burger");

        jLabel12.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Item Count");

        tfItem.setEditable(false);
        tfItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfItemActionPerformed(evt);
            }
        });

        bREMOVE.setBackground(new java.awt.Color(255, 102, 51));
        bREMOVE.setFont(new java.awt.Font("Lucida Bright", 0, 15)); // NOI18N
        bREMOVE.setForeground(new java.awt.Color(255, 255, 255));
        bREMOVE.setText("Clear");
        bREMOVE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bREMOVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bREMOVEActionPerformed(evt);
            }
        });

        bADD1.setBackground(new java.awt.Color(255, 102, 51));
        bADD1.setFont(new java.awt.Font("Lucida Bright", 0, 15)); // NOI18N
        bADD1.setForeground(new java.awt.Color(255, 255, 255));
        bADD1.setText("Back ");
        bADD1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bADD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bADD1ActionPerformed(evt);
            }
        });

        bADD2.setBackground(new java.awt.Color(255, 102, 51));
        bADD2.setFont(new java.awt.Font("Lucida Bright", 0, 15)); // NOI18N
        bADD2.setForeground(new java.awt.Color(255, 255, 255));
        bADD2.setText("View Cart");
        bADD2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bADD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bADD2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(jLabel10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(cbOnion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbChicken)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbPaneer, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(124, 124, 124)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sQuantity2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sQuantity1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49))
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfItem)
                            .addComponent(tfTotal)
                            .addComponent(bREMOVE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bADD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(198, 198, 198))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bADD1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(602, 602, 602)
                .addComponent(bADD2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(sQuantity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(cbChicken))
                                        .addGap(21, 21, 21)
                                        .addComponent(cbPaneer, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel11)
                                        .addComponent(sQuantity2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cbOnion)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(bADD, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bREMOVE, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfItem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bADD1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bADD2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 900, 480));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\OneDrive\\Desktop\\minor project materials\\burger resize.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbPaneerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPaneerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPaneerActionPerformed

    private void cbChickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbChickenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbChickenActionPerformed

    private void cbOnionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOnionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbOnionActionPerformed

    private void sQuantityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sQuantityStateChanged

        int Quantity = (Integer) sQuantity.getValue();
        if(Quantity < 1){
            sQuantity.setValue(0);
        }
    }//GEN-LAST:event_sQuantityStateChanged

    private void sQuantity2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sQuantity2StateChanged
        // TODO add your handling code here:
        int Quantity = (Integer) sQuantity2.getValue();
        if(Quantity < 1){
            sQuantity2.setValue(0);
        }
    }//GEN-LAST:event_sQuantity2StateChanged

    private void sQuantity1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sQuantity1StateChanged
        int Quantity = (Integer) sQuantity1.getValue();
        if(Quantity < 1){
            sQuantity1.setValue(0);
        }
    }//GEN-LAST:event_sQuantity1StateChanged

    private void tfTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTotalActionPerformed

    private void bADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bADDActionPerformed
        // TODO add your handling code here:
        //int Quantity = Integer.parseInt(tfQuantity.getText());
        //int Quantity1 = Integer.parseInt(tfQuantity1.getText());
        //int Quantity2 = Integer.parseInt(tfQuantity2.getText());

        double rate1 = 0;
        double rate2 = 0;
        double rate3 = 0;

        if(cbChicken.isSelected()){
            rate1 = 180;
        }
        if(cbPaneer.isSelected()){
            rate2 = 145;
        }
        if(cbOnion.isSelected()){
            rate3 = 119;
        }

        //double total2 = qty1 * rate1;
        //double total3 = qty2 * rate1;
        int Quantity = (Integer) sQuantity.getValue();
        if(Quantity < 1){
            sQuantity.setValue(0);
            Quantity = 0;
        }
        SubTotal = (int) (rate1 * Quantity);
        tfTotal.setText(String.valueOf(SubTotal));

        int Quantity1 = (Integer) sQuantity1.getValue();
        if(Quantity1 < 1){
            sQuantity1.setValue(0);
            Quantity1 = 0;
        }
        SubTotal1 = (int) ((rate2 * Quantity1)+SubTotal);
        tfTotal.setText(String.valueOf(SubTotal1));

        int Quantity2 = (Integer) sQuantity2.getValue();
        if(Quantity2 < 1){
            sQuantity2.setValue(0);
            Quantity2 = 0;
        }
        SubTotal2 = (int) ((rate3 * Quantity2)+SubTotal1);
        tfTotal.setText(String.valueOf(SubTotal2));

        int Quantity4 = 0;
        Quantity4 = Quantity + Quantity1 + Quantity2;
        tfItem.setText(String.valueOf(Quantity4));
        //double total1 =  rate1 * Quantity ;
        //double total2 =  rate1 * Quantity1 ;
        //double total3 =  rate1 * Quantity2 ;

        //tfTotal.setText("" +total1);
        //tfTotal.setText("" +total2);
        //tfTotal.setText("" +total3);
    }//GEN-LAST:event_bADDActionPerformed

    private void tfItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfItemActionPerformed

    private void bREMOVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bREMOVEActionPerformed
        // TODO add your handling code here:
        tfTotal.setText("");
        tfItem.setText("");
        sQuantity.setValue(0);
        sQuantity1.setValue(0);
        sQuantity2.setValue(0);
        cbChicken.setSelected(false);
        cbPaneer.setSelected(false);
        cbOnion.setSelected(false);
    }//GEN-LAST:event_bREMOVEActionPerformed

    private void bADD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bADD1ActionPerformed
        // TODO add your handling code here:
        BurgerHotel burger = new BurgerHotel();
        burger.setVisible(true);
    }//GEN-LAST:event_bADD1ActionPerformed

    private void bADD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bADD2ActionPerformed
        // TODO add your handling code here:
        BiggiesBurgerCart view = new BiggiesBurgerCart();
        view.LCount.setText(tfItem.getText());
        view.LTotal.setText(tfTotal.getText());
        view.setVisible(true);

        int tax = 17;
        int charge = 50;

        String str = tfTotal.getText();
        int Grand = Integer.parseInt(str);
        int Total = 0;
        //Grand =(Integer.parseInt((tfTotal) *17)/100)+50 + tfTotal;
        //view.LGrand.setText(tfTotal.setText(String.valueOf(Grand));
            Total = Grand + ((Grand*17)/100) + 50;
            view.LGrand.setText(String.valueOf(Total));
    }//GEN-LAST:event_bADD2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BiggiesBurger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BiggiesBurger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BiggiesBurger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BiggiesBurger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BiggiesBurger().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bADD;
    private javax.swing.JButton bADD1;
    private javax.swing.JButton bADD2;
    private javax.swing.JButton bREMOVE;
    private javax.swing.JCheckBox cbChicken;
    private javax.swing.JCheckBox cbOnion;
    private javax.swing.JCheckBox cbPaneer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner sQuantity;
    private javax.swing.JSpinner sQuantity1;
    private javax.swing.JSpinner sQuantity2;
    private javax.swing.JTextField tfItem;
    private javax.swing.JTextField tfTotal;
    // End of variables declaration//GEN-END:variables
}
